/* ────────────────────────────────────────────────────────────────
   Bull Market Finder — static universe data.

   S&P 500 constituents transcribed from the maintained
   datasets/s-and-p-500-companies GitHub dataset (fetched 2026-07-10;
   probe-verified reachable). Symbols are the dataset's native
   notation — dots (BRK.B) are translated to Yahoo dashes by the
   builder. Regenerate with `npm run refresh:universe` (needs
   network; not available in the build sandbox).

   Crypto and ETF lists are curated for reliable Yahoo servability;
   the refresh script upgrades crypto to the live CoinGecko top-100.
   Per-symbol isolation in the pipeline tolerates any misses.
──────────────────────────────────────────────────────────────── */

export const SP500_ASOF = "2026-07-10";

/** [ticker, display name] — dataset notation (dots, not dashes). */
export const SP500: ReadonlyArray<readonly [string, string]> = [
  ["MMM","3M"],["AOS","A. O. Smith"],["ABT","Abbott Laboratories"],["ABBV","AbbVie"],
  ["ACN","Accenture"],["ADBE","Adobe"],["AMD","Advanced Micro Devices"],["AES","AES Corp"],
  ["AFL","Aflac"],["A","Agilent"],["APD","Air Products"],["ABNB","Airbnb"],
  ["AKAM","Akamai"],["ALB","Albemarle"],["ARE","Alexandria RE"],["ALGN","Align Tech"],
  ["ALLE","Allegion"],["LNT","Alliant Energy"],["ALL","Allstate"],["GOOGL","Alphabet A"],
  ["GOOG","Alphabet C"],["MO","Altria"],["AMZN","Amazon"],["AMCR","Amcor"],
  ["AEE","Ameren"],["AEP","American Electric Power"],["AXP","American Express"],
  ["AIG","AIG"],["AMT","American Tower"],["AWK","American Water Works"],
  ["AMP","Ameriprise"],["AME","Ametek"],["AMGN","Amgen"],["APH","Amphenol"],
  ["ADI","Analog Devices"],["AON","Aon"],["APA","APA Corp"],["APO","Apollo Global"],
  ["AAPL","Apple"],["AMAT","Applied Materials"],["APP","AppLovin"],["APTV","Aptiv"],
  ["ACGL","Arch Capital"],["ADM","Archer Daniels Midland"],["ARES","Ares Management"],
  ["ANET","Arista Networks"],["AJG","Arthur J. Gallagher"],["AIZ","Assurant"],
  ["T","AT&T"],["ATO","Atmos Energy"],["ADSK","Autodesk"],["ADP","ADP"],
  ["AZO","AutoZone"],["AVB","AvalonBay"],["AVY","Avery Dennison"],["AXON","Axon"],
  ["BKR","Baker Hughes"],["BALL","Ball Corp"],["BAC","Bank of America"],
  ["BAX","Baxter"],["BDX","Becton Dickinson"],["BRK.B","Berkshire Hathaway"],
  ["BBY","Best Buy"],["TECH","Bio-Techne"],["BIIB","Biogen"],["BLK","BlackRock"],
  ["BX","Blackstone"],["XYZ","Block"],["BK","BNY Mellon"],["BA","Boeing"],
  ["BKNG","Booking"],["BSX","Boston Scientific"],["BMY","Bristol Myers Squibb"],
  ["AVGO","Broadcom"],["BR","Broadridge"],["BRO","Brown & Brown"],
  ["BF.B","Brown-Forman"],["BLDR","Builders FirstSource"],["BG","Bunge"],
  ["BXP","BXP"],["CHRW","C.H. Robinson"],["CDNS","Cadence"],["CPT","Camden Property"],
  ["CPB","Campbell's"],["COF","Capital One"],["CAH","Cardinal Health"],
  ["CCL","Carnival"],["CARR","Carrier"],["CVNA","Carvana"],["CASY","Casey's"],
  ["CAT","Caterpillar"],["CBOE","Cboe"],["CBRE","CBRE"],["CDW","CDW"],
  ["COR","Cencora"],["CNC","Centene"],["CNP","CenterPoint"],["CF","CF Industries"],
  ["CRL","Charles River Labs"],["SCHW","Charles Schwab"],["CHTR","Charter Comms"],
  ["CVX","Chevron"],["CMG","Chipotle"],["CB","Chubb"],["CHD","Church & Dwight"],
  ["CIEN","Ciena"],["CI","Cigna"],["CINF","Cincinnati Financial"],["CTAS","Cintas"],
  ["CSCO","Cisco"],["C","Citigroup"],["CFG","Citizens Financial"],["CLX","Clorox"],
  ["CME","CME Group"],["CMS","CMS Energy"],["KO","Coca-Cola"],["CTSH","Cognizant"],
  ["COHR","Coherent"],["COIN","Coinbase"],["CL","Colgate-Palmolive"],
  ["CMCSA","Comcast"],["FIX","Comfort Systems"],["CAG","Conagra"],
  ["COP","ConocoPhillips"],["ED","Consolidated Edison"],["STZ","Constellation Brands"],
  ["CEG","Constellation Energy"],["COO","Cooper"],["CPRT","Copart"],
  ["GLW","Corning"],["CPAY","Corpay"],["CTVA","Corteva"],["CSGP","CoStar"],
  ["COST","Costco"],["CTRA","Coterra"],["CRH","CRH"],["CRWD","CrowdStrike"],
  ["CCI","Crown Castle"],["CSX","CSX"],["CMI","Cummins"],["CVS","CVS Health"],
  ["DHR","Danaher"],["DRI","Darden"],["DDOG","Datadog"],["DVA","DaVita"],
  ["DECK","Deckers"],["DE","Deere"],["DELL","Dell"],["DAL","Delta Air Lines"],
  ["DVN","Devon Energy"],["DXCM","Dexcom"],["FANG","Diamondback"],
  ["DLR","Digital Realty"],["DG","Dollar General"],["DLTR","Dollar Tree"],
  ["D","Dominion"],["DPZ","Domino's"],["DASH","DoorDash"],["DOV","Dover"],
  ["DOW","Dow"],["DHI","D.R. Horton"],["DTE","DTE Energy"],["DUK","Duke Energy"],
  ["DD","DuPont"],["ETN","Eaton"],["EBAY","eBay"],["SATS","EchoStar"],
  ["ECL","Ecolab"],["EIX","Edison Intl"],["EW","Edwards Lifesciences"],
  ["EA","Electronic Arts"],["ELV","Elevance"],["EME","Emcor"],["EMR","Emerson"],
  ["ETR","Entergy"],["EOG","EOG Resources"],["EPAM","EPAM"],["EQT","EQT"],
  ["EFX","Equifax"],["EQIX","Equinix"],["EQR","Equity Residential"],
  ["ERIE","Erie Indemnity"],["ESS","Essex Property"],["EL","Estée Lauder"],
  ["EG","Everest Group"],["EVRG","Evergy"],["ES","Eversource"],["EXC","Exelon"],
  ["EXE","Expand Energy"],["EXPE","Expedia"],["EXPD","Expeditors"],
  ["EXR","Extra Space"],["XOM","ExxonMobil"],["FFIV","F5"],["FDS","FactSet"],
  ["FICO","Fair Isaac"],["FAST","Fastenal"],["FRT","Federal Realty"],["FDX","FedEx"],
  ["FIS","FIS"],["FITB","Fifth Third"],["FSLR","First Solar"],["FE","FirstEnergy"],
  ["FISV","Fiserv"],["F","Ford"],["FTNT","Fortinet"],["FTV","Fortive"],
  ["FOXA","Fox A"],["FOX","Fox B"],["BEN","Franklin Resources"],
  ["FCX","Freeport-McMoRan"],["GRMN","Garmin"],["IT","Gartner"],["GE","GE Aerospace"],
  ["GEHC","GE HealthCare"],["GEV","GE Vernova"],["GEN","Gen Digital"],
  ["GNRC","Generac"],["GD","General Dynamics"],["GIS","General Mills"],
  ["GM","General Motors"],["GPC","Genuine Parts"],["GILD","Gilead"],
  ["GPN","Global Payments"],["GL","Globe Life"],["GDDY","GoDaddy"],
  ["GS","Goldman Sachs"],["HAL","Halliburton"],["HIG","Hartford"],["HAS","Hasbro"],
  ["HCA","HCA Healthcare"],["DOC","Healthpeak"],["HSIC","Henry Schein"],
  ["HSY","Hershey"],["HPE","HPE"],["HLT","Hilton"],["HD","Home Depot"],
  ["HON","Honeywell"],["HRL","Hormel"],["HST","Host Hotels"],["HWM","Howmet"],
  ["HPQ","HP"],["HUBB","Hubbell"],["HUM","Humana"],["HBAN","Huntington Bancshares"],
  ["HII","Huntington Ingalls"],["IBM","IBM"],["IEX","IDEX"],["IDXX","Idexx"],
  ["ITW","Illinois Tool Works"],["INCY","Incyte"],["IR","Ingersoll Rand"],
  ["PODD","Insulet"],["INTC","Intel"],["IBKR","Interactive Brokers"],["ICE","ICE"],
  ["IFF","IFF"],["IP","International Paper"],["INTU","Intuit"],
  ["ISRG","Intuitive Surgical"],["IVZ","Invesco"],["INVH","Invitation Homes"],
  ["IQV","IQVIA"],["IRM","Iron Mountain"],["JBHT","J.B. Hunt"],["JBL","Jabil"],
  ["JKHY","Jack Henry"],["J","Jacobs"],["JNJ","Johnson & Johnson"],
  ["JCI","Johnson Controls"],["JPM","JPMorgan Chase"],["KVUE","Kenvue"],
  ["KDP","Keurig Dr Pepper"],["KEY","KeyCorp"],["KEYS","Keysight"],
  ["KMB","Kimberly-Clark"],["KIM","Kimco"],["KMI","Kinder Morgan"],["KKR","KKR"],
  ["KLAC","KLA"],["KHC","Kraft Heinz"],["KR","Kroger"],["LHX","L3Harris"],
  ["LH","Labcorp"],["LRCX","Lam Research"],["LVS","Las Vegas Sands"],
  ["LDOS","Leidos"],["LEN","Lennar"],["LII","Lennox"],["LLY","Eli Lilly"],
  ["LIN","Linde"],["LYV","Live Nation"],["LMT","Lockheed Martin"],["L","Loews"],
  ["LOW","Lowe's"],["LULU","Lululemon"],["LITE","Lumentum"],["LYB","LyondellBasell"],
  ["MTB","M&T Bank"],["MPC","Marathon Petroleum"],["MAR","Marriott"],
  ["MRSH","Marsh McLennan"],["MLM","Martin Marietta"],["MAS","Masco"],
  ["MA","Mastercard"],["MKC","McCormick"],["MCD","McDonald's"],["MCK","McKesson"],
  ["MDT","Medtronic"],["MRK","Merck"],["META","Meta"],["MET","MetLife"],
  ["MTD","Mettler Toledo"],["MGM","MGM Resorts"],["MCHP","Microchip"],
  ["MU","Micron"],["MSFT","Microsoft"],["MAA","Mid-America Apartment"],
  ["MRNA","Moderna"],["TAP","Molson Coors"],["MDLZ","Mondelez"],
  ["MPWR","Monolithic Power"],["MNST","Monster Beverage"],["MCO","Moody's"],
  ["MS","Morgan Stanley"],["MOS","Mosaic"],["MSI","Motorola Solutions"],
  ["MSCI","MSCI"],["NDAQ","Nasdaq Inc"],["NTAP","NetApp"],["NFLX","Netflix"],
  ["NEM","Newmont"],["NWSA","News Corp A"],["NWS","News Corp B"],
  ["NEE","NextEra"],["NKE","Nike"],["NI","NiSource"],["NDSN","Nordson"],
  ["NSC","Norfolk Southern"],["NTRS","Northern Trust"],["NOC","Northrop Grumman"],
  ["NCLH","Norwegian Cruise"],["NRG","NRG Energy"],["NUE","Nucor"],
  ["NVDA","Nvidia"],["NVR","NVR"],["NXPI","NXP"],["ORLY","O'Reilly"],
  ["OXY","Occidental"],["ODFL","Old Dominion"],["OMC","Omnicom"],
  ["ON","ON Semiconductor"],["OKE","Oneok"],["ORCL","Oracle"],["OTIS","Otis"],
  ["PCAR","Paccar"],["PKG","Packaging Corp"],["PLTR","Palantir"],
  ["PANW","Palo Alto Networks"],["PSKY","Paramount Skydance"],["PH","Parker Hannifin"],
  ["PAYX","Paychex"],["PYPL","PayPal"],["PNR","Pentair"],["PEP","PepsiCo"],
  ["PFE","Pfizer"],["PCG","PG&E"],["PM","Philip Morris"],["PSX","Phillips 66"],
  ["PNW","Pinnacle West"],["PNC","PNC"],["POOL","Pool Corp"],["PPG","PPG"],
  ["PPL","PPL"],["PFG","Principal Financial"],["PG","Procter & Gamble"],
  ["PGR","Progressive"],["PLD","Prologis"],["PRU","Prudential"],["PEG","PSEG"],
  ["PTC","PTC"],["PSA","Public Storage"],["PHM","PulteGroup"],["PWR","Quanta"],
  ["QCOM","Qualcomm"],["DGX","Quest Diagnostics"],["Q","Qnity Electronics"],
  ["RL","Ralph Lauren"],["RJF","Raymond James"],["RTX","RTX"],["O","Realty Income"],
  ["REG","Regency Centers"],["REGN","Regeneron"],["RF","Regions Financial"],
  ["RSG","Republic Services"],["RMD","ResMed"],["RVTY","Revvity"],
  ["HOOD","Robinhood"],["ROK","Rockwell"],["ROL","Rollins"],["ROP","Roper"],
  ["ROST","Ross Stores"],["RCL","Royal Caribbean"],["SPGI","S&P Global"],
  ["CRM","Salesforce"],["SNDK","Sandisk"],["SBAC","SBA Comms"],
  ["SLB","Schlumberger"],["STX","Seagate"],["SRE","Sempra"],["NOW","ServiceNow"],
  ["SHW","Sherwin-Williams"],["SPG","Simon Property"],["SWKS","Skyworks"],
  ["SJM","J.M. Smucker"],["SW","Smurfit Westrock"],["SNA","Snap-on"],
  ["SOLV","Solventum"],["SO","Southern Co"],["LUV","Southwest Airlines"],
  ["SWK","Stanley Black & Decker"],["SBUX","Starbucks"],["STT","State Street"],
  ["STLD","Steel Dynamics"],["STE","Steris"],["SYK","Stryker"],["SMCI","Supermicro"],
  ["SYF","Synchrony"],["SNPS","Synopsys"],["SYY","Sysco"],["TMUS","T-Mobile"],
  ["TROW","T. Rowe Price"],["TTWO","Take-Two"],["TPR","Tapestry"],
  ["TRGP","Targa Resources"],["TGT","Target"],["TEL","TE Connectivity"],
  ["TDY","Teledyne"],["TER","Teradyne"],["TSLA","Tesla"],["TXN","Texas Instruments"],
  ["TPL","Texas Pacific Land"],["TXT","Textron"],["TMO","Thermo Fisher"],
  ["TJX","TJX"],["TKO","TKO Group"],["TTD","Trade Desk"],["TSCO","Tractor Supply"],
  ["TT","Trane"],["TDG","TransDigm"],["TRV","Travelers"],["TRMB","Trimble"],
  ["TFC","Truist"],["TYL","Tyler Tech"],["TSN","Tyson Foods"],["USB","U.S. Bancorp"],
  ["UBER","Uber"],["UDR","UDR"],["ULTA","Ulta Beauty"],["UNP","Union Pacific"],
  ["UAL","United Airlines"],["UPS","UPS"],["URI","United Rentals"],
  ["UNH","UnitedHealth"],["UHS","Universal Health"],["VLO","Valero"],
  ["VTR","Ventas"],["VLTO","Veralto"],["VRSN","Verisign"],["VRSK","Verisk"],
  ["VZ","Verizon"],["VRTX","Vertex Pharma"],["VRT","Vertiv"],["VTRS","Viatris"],
  ["VICI","Vici Properties"],["V","Visa"],["VST","Vistra"],["VMC","Vulcan Materials"],
  ["WRB","W. R. Berkley"],["GWW","W. W. Grainger"],["WAB","Wabtec"],
  ["WMT","Walmart"],["DIS","Disney"],["WBD","Warner Bros. Discovery"],
  ["WM","Waste Management"],["WAT","Waters"],["WEC","WEC Energy"],
  ["WFC","Wells Fargo"],["WELL","Welltower"],["WST","West Pharmaceutical"],
  ["WDC","Western Digital"],["WY","Weyerhaeuser"],["WSM","Williams-Sonoma"],
  ["WMB","Williams Companies"],["WTW","Willis Towers Watson"],["WDAY","Workday"],
  ["WYNN","Wynn Resorts"],["XEL","Xcel Energy"],["XYL","Xylem"],["YUM","Yum! Brands"],
  ["ZBRA","Zebra"],["ZBH","Zimmer Biomet"],["ZTS","Zoetis"],
];

/** Nasdaq-100 members not in the S&P 500 (curated; deduped at build). */
export const NDX_EXTRA: ReadonlyArray<readonly [string, string]> = [
  ["ARM","Arm Holdings"],["ASML","ASML"],["AZN","AstraZeneca"],
  ["MELI","MercadoLibre"],["PDD","PDD Holdings"],["TEAM","Atlassian"],
  ["ZS","Zscaler"],["MRVL","Marvell"],["MDB","MongoDB"],["OKTA","Okta"],
];

/** Curated crypto majors, Yahoo `-USD` notation. Reliable Yahoo
 *  servability preferred over completeness — the refresh script
 *  upgrades this to the live CoinGecko top-100 when run with
 *  network. Per-symbol isolation tolerates any delistings. */
export const CRYPTO: ReadonlyArray<readonly [string, string]> = [
  ["BTC-USD","Bitcoin"],["ETH-USD","Ethereum"],["XRP-USD","XRP"],["BNB-USD","BNB"],
  ["SOL-USD","Solana"],["DOGE-USD","Dogecoin"],["ADA-USD","Cardano"],["TRX-USD","TRON"],
  ["LINK-USD","Chainlink"],["AVAX-USD","Avalanche"],["XLM-USD","Stellar"],["SUI-USD","Sui"],
  ["BCH-USD","Bitcoin Cash"],["HBAR-USD","Hedera"],["LTC-USD","Litecoin"],["DOT-USD","Polkadot"],
  ["SHIB-USD","Shiba Inu"],["UNI-USD","Uniswap"],["PEPE-USD","Pepe"],["AAVE-USD","Aave"],
  ["NEAR-USD","NEAR"],["APT-USD","Aptos"],["ICP-USD","Internet Computer"],["ETC-USD","Ethereum Classic"],
  ["RENDER-USD","Render"],["VET-USD","VeChain"],["ARB-USD","Arbitrum"],["OP-USD","Optimism"],
  ["FIL-USD","Filecoin"],["ATOM-USD","Cosmos"],["KAS-USD","Kaspa"],["INJ-USD","Injective"],
  ["IMX-USD","Immutable"],["STX-USD","Stacks"],["GRT-USD","The Graph"],["TAO-USD","Bittensor"],
  ["SEI-USD","Sei"],["LDO-USD","Lido DAO"],["THETA-USD","Theta"],["ALGO-USD","Algorand"],
  ["EGLD-USD","MultiversX"],["FLOW-USD","Flow"],["XTZ-USD","Tezos"],["SAND-USD","The Sandbox"],
  ["MANA-USD","Decentraland"],["AXS-USD","Axie Infinity"],["CRV-USD","Curve"],["MKR-USD","Maker"],
  ["ENS-USD","ENS"],["QNT-USD","Quant"],["GALA-USD","Gala"],["CHZ-USD","Chiliz"],
  ["ZEC-USD","Zcash"],["DASH-USD","Dash"],["EOS-USD","EOS"],["XMR-USD","Monero"],
  ["FET-USD","Artificial Superintelligence"],["ONDO-USD","Ondo"],["JUP-USD","Jupiter"],["WIF-USD","dogwifhat"],
];

/** Curated liquid ETFs (deduped against the macro tier at build). */
export const ETFS: ReadonlyArray<readonly [string, string]> = [
  ["SPY","S&P 500 ETF"],["QQQ","Nasdaq 100 ETF"],["DIA","Dow ETF"],["IWM","Russell 2000 ETF"],
  ["VTI","Total US Market"],["EFA","Developed ex-US"],["EEM","Emerging Markets"],["VWO","EM Vanguard"],
  ["FXI","China Large-Cap"],["MCHI","China MSCI"],["EWJ","Japan"],["EWZ","Brazil"],
  ["EWG","Germany"],["EWU","United Kingdom"],["INDA","India"],["XLK","Technology"],
  ["XLF","Financials"],["XLV","Health Care"],["XLI","Industrials"],["XLY","Consumer Discretionary"],
  ["XLP","Consumer Staples"],["XLU","Utilities"],["XLB","Materials"],["XLRE","Real Estate"],
  ["XLC","Communication Services"],["SMH","Semiconductors"],["SOXX","Semiconductors iShares"],["XBI","Biotech SPDR"],
  ["IBB","Biotech iShares"],["KRE","Regional Banks"],["KBE","Banks"],["ITB","Home Construction"],
  ["XHB","Homebuilders"],["JETS","Airlines"],["XRT","Retail"],["XOP","Oil & Gas E&P"],
  ["OIH","Oil Services"],["TAN","Solar"],["URA","Uranium"],["LIT","Lithium & Battery"],
  ["ARKK","ARK Innovation"],["GLD","Gold ETF"],["SLV","Silver ETF"],["GDXJ","Junior Gold Miners"],
  ["USO","US Oil Fund"],["UNG","US Natural Gas"],["DBC","Commodity Index"],["DBA","Agriculture"],
  ["IBIT","iShares Bitcoin"],["COPX","Copper Miners"],
];
